# Generated by Django 6.1 on 2026-08-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
