# Generated by Django 6.1 on 2026-08-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Título'),
        ),
    ]
